language: python 

python: 
- "3.6"

services:
- postgresql

env: 
- DJANGO=2.0 DB=postgres

global:
- PGPORT=5432

install: 
- pip3 install -r requirements.txt

before_script:
- cd decide
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"
- python3 manage.py makemigrations
- python3 manage.py migrate

script: 
- python3 manage.py test

addons:
postgresql: '9.6'
