language: python 

python: 
- "3.6"

services:
- postgresql

env: 
- DJANGO=2.0 DB=postgres

global:
- PGPORT=5432

install: 
- pip3 install -r requirements.txt

before_script:
- cd decide
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"
- python3 manage.py makemigrations
- python3 manage.py migrate

script: 
- python3 manage.py test 
- if [[ $TRAVIS_BRANCH == master ]] && [[ $DEPLOY_TRAVIS == "1" ]]; then git archive --format zip --output ./decide.zip master; echo "Zip generado correctamente."; fi

before_deploy:
- git config --local user.name marjimveg1
- git config --local user.email maria-2696@hotmail.com
- export YEAR=`date +"%Y"`  
- export GIT_TAG=v$MILESTONE_TRAVIS.0.$TRAVIS_BUILD_NUMBER
- git tag -a $GIT_TAG -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"



addons:
postgresql: '9.6'
