language: python 

python: 
- "3.6"

addons:
  postgresql: "9.6"
  services:
  - postgresql
  
env: 
- DJANGO=2.0 DB=postgres

before_install: 
- cd decide

install: 
- pip install -r ../requirements-build.txt

script: 
- cd visualizer
- cd ..

before_script: 
- cp local_settings.example.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"
- python manage.py migrate

